version: '3.7'

services:
  pangu:
    build: ../
    container_name: 'pangu'
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - build:/usr/src/app/build
  # pangu_web:
  #   image: nginx
  #   ports:
  #     - 8000:80
  #   container_name: "pangu_web"
  #   restart: unless-stopped
  #   volumes:
  #     - build:/usr/share/nginx/html:ro
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  build:
